name: "tests"
on:
  pull_request:
  push:
    branches:
      - master
      - main
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install libxls
        run: |
          wget https://github.com/libxls/libxls/releases/download/v1.6.2/libxls-1.6.2.tar.gz \
          && tar -xzvf libxls-1.6.2.tar.gz \
          && cd libxls-1.6.2 \
          && ./configure \
          && sudo make \
          && sudo make install \
          && sudo ldconfig /etc/ld.so.conf.d
        shell: bash

      - name: Test
        run: CGO_LDFLAGS=-lxlsreader go test ./...

      - name: Calc coverage
        run: |
          CGO_LDFLAGS=-lxlsreader go test -coverpkg=./... ./... -count=1 -coverprofile=cover.cov.tmp -v
          cat cover.cov.tmp | grep -v "main.go" > profile.cov

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
